/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Loading1: typeof import('./../src/components/s-loading/loading1.vue')['default']
    Loading2: typeof import('./../src/components/s-loading/loading2.vue')['default']
    Loading3: typeof import('./../src/components/s-loading/loading3.vue')['default']
    Loading4: typeof import('./../src/components/s-loading/loading4.vue')['default']
    Loading5: typeof import('./../src/components/s-loading/loading5.vue')['default']
    Loading6: typeof import('./../src/components/s-loading/loading6.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SBackground: typeof import('./../src/components/s-background/index.vue')['default']
    SCar: typeof import('./../src/components/s-car/index.vue')['default']
    SEmpty: typeof import('./../src/components/s-empty/index.vue')['default']
    SLoading: typeof import('./../src/components/s-loading/index.vue')['default']
    SLottery: typeof import('./../src/components/s-lottery/index.vue')['default']
    SPopup: typeof import('./../src/components/s-popup/index.vue')['default']
    SProgress: typeof import('./../src/components/s-progress/index.vue')['default']
    SSpace: typeof import('./../src/components/s-space/index.vue')['default']
  }
}
